import type { Metadata } from "next";
import "./globals.css";
import { SidebarProvider } from "@/shared/ui/layout/sidebar";
import { Toaster } from "@/shared/ui/overlay/sonner";

// TODO: SEO

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
      <body
        className={`antialiased`}
      >
        <SidebarProvider>
          <Toaster />
          {children}
        </SidebarProvider>
      </body>
    </html>
  );
}
