version: '3.7'

services:
    db-main:
        container_name: postgres-bot-main
        image: postgres:latest
        restart: always
        env_file:
            - .env.main
        ports:
            - "5433:5432"
        volumes:
            - postgres_main_data:/var/lib/postgresql/data
        networks:
            - bot-backend

    db-dev:
        container_name: postgres-bot-dev
        image: postgres:latest 
        restart: always
        env_file:
            - .env.dev
        ports:
            - "5434:5432"
        volumes:
            - postgres_dev_data:/var/lib/postgresql/data
        networks:
            - bot-backend

    redis-main:
        container_name: redis-bot-main
        image: redis:6.0
        restart: always
        env_file:
            - .env.main
        ports:
            - "6379:6379"
        command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
        volumes:
            - redis_main_data:/data
        networks:
            - bot-backend

    redis-dev:
        container_name: redis-bot-dev
        image: redis:6.0
        restart: always
        env_file:
            - .env.dev
        ports:
            - "6380:6379"
        command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
        volumes:
            - redis_dev_data:/data
        networks:
            - bot-backend
    # minio:
    #     image: minio/minio
    #     container_name: minio-bot
    #     ports:
    #     - "9000:9000"
    #     - "9001:9001"
    #     environment:
    #     MINIO_ACCESS_KEY: minio
    #     MINIO_SECRET_KEY: minio123
    #     command: server /data --console-address ":9001"
    #     volumes:
    #     - minio_data:/data
    #     networks:
    #     - bot-backend
            
volumes:
    postgres_main_data:
    postgres_dev_data:
    redis_main_data:
    redis_dev_data:
    minio_data:

networks:
    bot-backend: