[project]
name = "referalbot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "aiogram==3.0.0b7",
    "psycopg2>=2.9.10",
]
