name: Test Frontend

on:
  workflow_dispatch:
  workflow_call:

jobs:
  frontend:
    name: Test frontend
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        node-version: [ 22.11.0 ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Staring Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: |
          cd frontend
          npm ci --legacy-peer-deps
      - name: Build project
        run: |
          cd frontend
          npm run build
      - name: Start project
        run: |
          cd frontend
          npm run start -- --port 5000 &
          echo $! > ../frontend.pid
      - name: Check the application availability after a 10 seconds
        run: |
          sleep 10s
          HTTP_STATUS=$(curl --write-out '%{http_code}' --silent --output /dev/null http://127.0.0.1:5000)
          kill $(cat frontend.pid)
          if [[ "$HTTP_STATUS" -ne 200 ]]; then exit 1; fi